"""Cards: the documentation half of a metric or degradation bundle.

A **bundle** is one directory holding everything about one metric or one degradation:
the implementation, its tests, its references, its card, and the evidence generated by
running it. The card is the part that explains the thing to a reader, and it comes in
two halves:

``card.yaml``
    The typed half. Anything a machine can check, compare, or filter on lives here:
    the category, the status, the output's bounds, the predicted responses, the
    reference keys, the review ledger. :mod:`fmeval.cards.schema` is the single
    definition of what is allowed, and nothing else may hard-code field names.

``card.md``
    The prose half. Required sections in a fixed order, written for three readers: a
    STEM undergraduate from any field, a domain expert, and a coding agent. Two of its
    sections are generated and must not be hand-written.

The split exists so that a claim about a metric is either machine-checkable or clearly
marked as prose, and so that documentation cannot be quietly omitted: a bundle without a
valid card fails when the metric is requested, not months later when someone reads it.

Deliberately no third-party dependency
--------------------------------------
Validation is hand-written on stdlib dataclasses rather than delegated to a schema
library. Two reasons, in order of weight:

1. This repository is developed on NERSC login nodes, where ``uv`` is unavailable, so a
   new runtime dependency cannot be added to the committed lockfile from the machine
   the work happens on. CI runs ``uv sync --locked`` and would fail on the mismatch.
2. The registries in ``metrics/``, ``degradations/`` and ``fmeval/report/`` already
   validate their own specs by hand, and the error messages they produce are better
   than a generic library's because they name the fix. Cards hold that bar: every
   failure states the bundle, what was expected, and the command that repairs it.

Schema versioning
-----------------
Every card records ``schema_version``. Additive, backwards-compatible changes keep the
version. A change that would invalidate an existing card bumps
:data:`~fmeval.cards.schema.SCHEMA_VERSION` and adds a ``migrate_vN_to_vN_plus_1``
function in :mod:`fmeval.cards.schema`, which the loader applies with a warning. The
loader refuses a card written by a newer schema than it knows, rather than guessing.
"""

from __future__ import annotations

from .schema import SCHEMA_VERSION, Card, CardError

__all__ = ["SCHEMA_VERSION", "Card", "CardError"]
