"""Find bundles on disk, load their cards, and check them against the code.

A **bundle** is a directory under ``metrics/`` or ``degradations/`` holding one metric or
one degradation and everything that documents it. This module is the only place that
knows the directory layout; everything else asks here.

Where enforcement happens, and why not at import
------------------------------------------------
The obvious way to make a card unskippable is to validate it when the module is imported,
so a bundle without a card cannot even load. That is rejected here for a specific reason:
discovery imports *every* module in the package, so a colleague's half-finished card in
one bundle would break ``evaluate.py`` for everyone running an unrelated metric. It would
also make ``metrics/`` depend on this package, which imports pandas and matplotlib, when
today it needs only numpy.

Instead the registries expose a validation hook that this module installs. Asking for a
metric by name validates *that* metric's card, so you cannot run something undocumented,
while an unrelated broken card stays a broken card. The parametrized tests in
``tests/test_cards.py`` check all bundles at once, which is where a repository-wide
problem should surface.
"""

from __future__ import annotations

import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from .schema import Card, CardError, parse_card

BUNDLE_FILES = ("card.yaml", "card.md", "refs.bib")
"""Files every bundle must contain, whatever it holds."""

GENERATED_DIR = "_generated"
"""Build output. Never hand-edited; regenerated by ``python -m fmeval.cards``."""

SKIP_ENV = "FMEVAL_SKIP_CARD_CHECK"
"""Set to ``1`` to bypass card validation. For debugging only, and it says so loudly."""


@dataclass(frozen=True)
class Bundle:
    """One bundle directory and the paths inside it."""

    name: str
    kind: str
    path: Path

    @property
    def card_yaml(self) -> Path:
        return self.path / "card.yaml"

    @property
    def card_md(self) -> Path:
        return self.path / "card.md"

    @property
    def refs(self) -> Path:
        return self.path / "refs.bib"

    @property
    def generated(self) -> Path:
        return self.path / GENERATED_DIR

    @property
    def implementation(self) -> Path:
        return self.path / ("metric.py" if self.kind == "metric" else "degradation.py")


def repo_root() -> Path:
    """The repository root, found from this file rather than the working directory.

    Nothing in this repository requires being run from the root, so the root cannot be
    inferred from ``cwd``.
    """
    return Path(__file__).resolve().parent.parent.parent


def bundle_root(kind: str) -> Path:
    """The directory holding all bundles of one kind."""
    if kind not in ("metric", "degradation"):
        raise ValueError(f"unknown bundle kind {kind!r}")
    return repo_root() / ("metrics" if kind == "metric" else "degradations")


def iter_bundles(kind: str | None = None) -> list[Bundle]:
    """Every bundle on disk, sorted by name.

    A directory counts as a bundle when it contains a ``card.yaml``. Directories whose
    name starts with an underscore are skipped: those are templates and shared helpers,
    which are deliberately not bundles.

    Args:
        kind: ``"metric"``, ``"degradation"``, or ``None`` for both.

    Returns:
        The bundles found, sorted by (kind, name).
    """
    kinds = ("metric", "degradation") if kind is None else (kind,)
    found: list[Bundle] = []
    for k in kinds:
        root = bundle_root(k)
        if not root.is_dir():
            continue
        for entry in sorted(root.iterdir()):
            if not entry.is_dir() or entry.name.startswith(("_", ".")):
                continue
            if (entry / "card.yaml").is_file():
                found.append(Bundle(name=entry.name, kind=k, path=entry))
    return found


def find_bundle(name: str, kind: str | None = None) -> Bundle | None:
    """The bundle registered under ``name``, or ``None`` if there is no such directory."""
    for bundle in iter_bundles(kind):
        if bundle.name == name:
            return bundle
    return None


def bundle_for_module(module: str, name: str, kind: str) -> Bundle | None:
    """Locate the bundle that defines an already-imported module.

    The registries record ``fn.__module__`` rather than a path, so the file is recovered
    from :data:`sys.modules`. This is what lets card validation work for a bundle that was
    imported from an installed copy of the package rather than from the checkout.

    Args:
        module: Dotted module name, as recorded on the spec.
        name: Registered name, used to confirm the directory matches.
        kind: ``"metric"`` or ``"degradation"``.

    Returns:
        The bundle, or ``None`` if the module does not live in one.
    """
    mod = sys.modules.get(module)
    file = getattr(mod, "__file__", None)
    if file is None:
        return None
    directory = Path(file).resolve().parent
    if not (directory / "card.yaml").is_file():
        return None
    return Bundle(name=directory.name, kind=kind, path=directory)


def load_card(bundle: Bundle) -> Card:
    """Read and validate one bundle's ``card.yaml``.

    Args:
        bundle: The bundle to read.

    Returns:
        The validated card.

    Raises:
        CardError: If the file is missing, unparseable, invalid, or disagrees with the
            directory it sits in.
    """
    path = bundle.card_yaml
    if not path.is_file():
        raise CardError(
            str(path),
            "this bundle has no card, so nothing records what it measures or how to "
            "read its output.",
            f"python -m fmeval.cards new {bundle.name} --kind {bundle.kind}",
        )
    try:
        data = yaml.safe_load(path.read_text()) or {}
    except yaml.YAMLError as exc:
        raise CardError(str(path), f"the file is not valid YAML: {exc}", "fix the syntax") from exc

    card = parse_card(data, where=str(path))

    if card.name != bundle.name:
        raise CardError(
            str(path),
            f"card name is {card.name!r} but the directory is {bundle.name!r}. The name "
            "is the metric's identity and the two must agree.",
            f"rename one of them so both read {bundle.name!r}",
        )
    if card.kind != bundle.kind:
        raise CardError(
            str(path),
            f"card kind is {card.kind!r} but the bundle lives under "
            f"{bundle_root(bundle.kind).name}/.",
            f"set kind: {bundle.kind}",
        )
    return card


def check_bundle_files(bundle: Bundle) -> list[str]:
    """Report which required files a bundle is missing.

    Args:
        bundle: The bundle to inspect.

    Returns:
        Problems as human-readable sentences; empty when the bundle is complete.
    """
    problems = []
    for filename in BUNDLE_FILES:
        if not (bundle.path / filename).is_file():
            problems.append(f"{filename} is missing")
    if not bundle.implementation.is_file():
        problems.append(f"{bundle.implementation.name} is missing")
    return problems


# --------------------------------------------------------------------------------------
# The registry hook
# --------------------------------------------------------------------------------------


def _validate_spec(spec: Any, kind: str) -> None:
    """Validate the card of a metric or degradation as it is requested by name.

    Installed onto the registries by :func:`install`. Raising here is the point: asking
    the harness to run something whose documentation is missing or wrong should fail
    immediately, with the command that fixes it, rather than producing numbers nobody can
    interpret later.
    """
    if os.environ.get(SKIP_ENV) == "1":
        return
    bundle = bundle_for_module(spec.module, spec.name, kind)
    if bundle is None:
        # Not in a bundle at all. Tests register throwaway metrics this way on purpose,
        # and so does anyone experimenting in a notebook, so this is not an error.
        return
    load_card(bundle)


def install() -> None:
    """Point the metric and degradation registries at the card validator.

    Called from :mod:`fmeval` so that every path through the harness enforces cards,
    while ``import metrics`` on its own stays free of this package and its dependencies.
    """
    from degradations import registry as deg_registry
    from metrics import registry as metric_registry

    metric_registry.CARD_VALIDATOR = lambda spec: _validate_spec(spec, "metric")
    deg_registry.CARD_VALIDATOR = lambda spec: _validate_spec(spec, "degradation")
